logic/.editorconfig
logic/Preparation/Constant.cs
logic/Preparation/GameObj/GameObj.cs
logic/Preparation/Interface/IGameObj.cs
logic/Preparation/Preparation.csproj
logic/Preparation/Utility/Constant.cs
logic/Preparation/Utility/EnumType.cs
logic/Server/Server.csproj
logic/logic.sln

refactor!: change Preparation to Class Library, move ALL enum types from their Interface/GameObj files to a new file EnumType.cs, add Constant.cs.

---

dependency/proto/Message2Clients.proto
dependency/proto/Message2Server.proto
dependency/proto/MessageType.proto
logic/GameClass/GameObj/Character.SkillManager.cs
logic/GameClass/GameObj/Character.cs
logic/GameClass/Skill/CommonSkill.cs
logic/GameClass/Skill/Skill.cs
logic/Gaming/AttackManager.cs

Refactor: Refactor the logic of CommonSkill

---

communication/ClientCommunication/ClientCommunication.cs
communication/ClientTest/Program.cs
communication/Proto/Message.cs
communication/ServerCommunication/ServerCommunication.cs
communication/ServerTest/Program.cs
dependency/proto/Message2Clients.proto

3.0 版本去掉了所有的oneof，server组件也需要更改。同时修复了之前单播的bug，现在server和client之间的反馈也更完善了。

refactor: refactor the server

---

logic/Gaming/Game.cs
logic/Message.md
logic/Server/GameServer.cs
logic/Test/Program.cs
logic/cmd/runServer.cmd

docs: add instructions of message

---

SECURITY.md

chore(repo): Setup security policy

---

logic/UnPreparedFunction/Program.cs

Add mapCreater

---

logic/Client/MainWindow.xaml.cs
logic/UnPreparedFunction/Program.cs

Updated: small changes on random map 

---

logic/Client/MainWindow.xaml.cs
logic/GameClass/GameObj/Character.cs
logic/GameClass/GameObj/Map/Map.cs
logic/GameClass/GameObj/Map/MapInfo.cs
logic/GameClass/Skill/CommonSkill.cs
logic/Gaming/GemManager.cs
logic/Gaming/PropManager.cs
logic/Server/ArgumentOption.cs
logic/Server/GameServer.cs

fix: fix some bugs

---

logic/GameClass/GameObj/Character.SkillManager.cs
logic/GameClass/GameObj/Character.cs
logic/GameClass/GameObj/Map/GemWell.cs
logic/GameClass/GameObj/Map/Grass.cs
logic/GameClass/GameObj/Map/Map.cs
logic/GameClass/GameObj/Map/Wall.cs
logic/GameClass/Skill/CommonSkill.cs
logic/GameClass/Skill/PassiveSkill.cs
logic/GameClass/Skill/Skill.cs
logic/GameEngine/CollisionChecker.cs
logic/Preparation/Interface/IMap.cs
logic/Preparation/Interface/IMoveable.cs
logic/Server/PlaybackServer.cs

fix: fixed bugs of walking in walls by searching comparing distance to all walls

---

renovate.json

chore(bot): disable automatical update of hpsocket.net by renovate

---

renovate.json

fix(bot): the bug that cannot disable automatical update of hpsocket.net

---

renovate.json

chore(bot): set the version of hpsocket.net to <= 5.8.4.1

---

logic/CSharpInterface/ClientInterface.cs
logic/CSharpInterface/Competitor.cs
logic/CSharpInterface/Constants.cs
logic/CSharpInterface/Program.cs
logic/cmd/CSharpClient.cmd

chore: Add a simple AI

---

.github/FUNDING.yml

chore(fund): init sponsorship

---

CAPI/API/include/API.h

fix: change macro to constexpr

---

CAPI/proto/Message2Clients.pb.cc
CAPI/proto/Message2Clients.pb.h
communication/Proto/Message2Clients.cs
dependency/proto/Message2Clients.proto
logic/Preparation/Utility/EnumType.cs
logic/Server/CopyInfo.cs
logic/cmd/playbackServer.cmd

chore: add character's facingdirection in proto

---

CAPI/proto/Message2Clients.pb.cc
CAPI/proto/Message2Clients.pb.h
CAPI/proto/MessageType.pb.cc
CAPI/proto/MessageType.pb.h
communication/Proto/Message2Clients.cs
communication/Proto/MessageType.cs
dependency/proto/Message2Clients.proto
dependency/proto/MessageType.proto
logic/GameClass/GameObj/Character.BuffManager.cs
logic/GameClass/GameObj/Character.SkillManager.cs
logic/GameClass/GameObj/Character.cs
logic/GameClass/GameObj/Prop.cs
logic/Server/CopyInfo.cs

chore: send buffarray to clients

---

playback/PlayBack/PlayBack.csproj

refactor: enable nullable checking in playback

---

dependency/Dockerfile/Dockerfile_compile
dependency/shell/compile.sh

modified:   dependency/Dockerfile/Dockerfile_compile
modified:   dependency/shell/compile.sh

chore: modified the dockerfile of compiler and compile.sh

---

logic/GameClass/GameObj/Bullet.cs
logic/GameClass/GameObj/Character.SkillManager.cs
logic/GameClass/GameObj/Character.cs
logic/GameClass/GameObj/ObjOfCharacter.cs
logic/GameClass/Skill/CommonSkill.cs
logic/GameClass/Skill/ISkill.cs
logic/GameClass/Skill/PassiveSkill.cs
logic/Gaming/AttackManager.cs
logic/Gaming/GemManager.cs
logic/Gaming/PropManager.cs
logic/Server/CopyInfo.cs
logic/Server/Properties/launchSettings.json
logic/bash/csharpclient.sh
logic/bash/gameServer_1.sh
logic/cmd/CSharpClient.cmd
logic/cmd/gameServer.cmd

fix: fix a bug of readerwriter lock in server

---

dependency/Dockerfile/Dockerfile_compile
dependency/shell/compile.sh

chore: modified Dockerfile_compile and compile.sh

---

logic/Server/PlaybackServer.cs
logic/Test/Program.cs
logic/cmd/playbackServer.cmd
logic/cmd/testClient.cmd

fix: fix duplicate players

---

CAPI/CAPI.md

chore : changing the CAPI.md

---

CAPI/API/include/structures.h

chore: add description in CAPI

---

logic/Gaming/GemManager.cs
logic/Gaming/PropManager.cs
logic/Server/GameServer.cs
logic/Test/Program.cs
logic/cmd/gameServer.cmd
logic/cmd/playbackServer.cmd

fix: fix a bug of not sending pickedprop

---

logic/Server/GameServer.cs

fix: fix a bug of http sender

---

logic/Server/GameServer.cs
logic/cmd/gameServer.cmd

chore: rm space in result.json

---

dependency/Dockerfile/Dockerfile_run
dependency/shell/compile.sh
dependency/shell/run.sh

chore: modified shell scripts for docker images and dockerfile

---

CAPI/API/include/structures.h
logic/Client/MainWindow.xaml.cs
logic/GameClass/GameObj/Character.cs
logic/Gaming/GemManager.cs
logic/Gaming/PropManager.cs
logic/cmd/gameServer.cmd
playback/PlayBack/MessageWriter.cs

fix: fix concurrent bugs of props

---

logic/Gaming/GemManager.cs
logic/cmd/CSharpClient.cmd
logic/cmd/gameServer.cmd

fix: fix a bug of throwing gems

---

logic/GameClass/GameObj/Character.cs
logic/GameClass/Skill/CommonSkill.cs
logic/GameClass/Skill/ISkill.cs
logic/Preparation/Interface/ICharacter.cs
logic/cmd/gameServer.cmd

fix: fix a bug of skill

---

dependency/shell/compile.sh
dependency/shell/run.sh

chore: modified shell scripts for compiler and runner

---

logic/GameClass/GameObj/Character.cs
logic/Gaming/GemManager.cs
logic/cmd/gameServer.cmd

fix: fix a bug of using gems concurrently

---

logic/GameClass/GameObj/Character.cs
logic/GameClass/GameObj/GameObj.cs

fix: fix a possible bug of resetting

---

dependency/shell/run.sh

chore: modified run.sh

---

logic/GameClass/GameObj/Bullet.cs
logic/GameClass/GameObj/Character.SkillManager.cs
logic/GameClass/GameObj/Character.cs
logic/GameClass/Skill/CommonSkill.cs
logic/GameClass/Skill/ISkill.cs
logic/GameClass/Skill/PassiveSkill.cs
logic/cmd/gameServer.cmd

refactor: change the skill structure

---

CAPI/proto/Message2Clients.pb.cc
CAPI/proto/Message2Clients.pb.h
communication/Proto/Message2Clients.cs
dependency/proto/Message2Clients.proto
logic/GameClass/GameObj/Bullet.cs
logic/Server/CopyInfo.cs
logic/cmd/gameServer.cmd

chore: add bullet bomb range in proto

---

dependency/shell/run.sh

chore: add function for map selection in run.sh

---

logic/GameEngine/MoveEngine.cs

fix: fix a bug of server crashed

---

logic/GameClass/Skill/CommonSkill.cs

fix: fix character's params
